plugins { id 'com.android.application' }

android {
    namespace 'com.aivo.mijaspub'
    compileSdk 34

    defaultConfig {
        applicationId "com.aivo.mijaspub"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.10.01"
    }

    // Kiinteä allekirjoitusavain -> jokainen build on sama allekirjoitus,
    // joten paivitykset asentuvat vanhan paalle ja DATA SAILYY.
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.11.0'
}
